# column_order_config.py
# -----------------------------------------------------------
# Hard-coded column-ordering rules
# -----------------------------------------------------------
COLUMN_ORDER_CONFIG = [
    # | Project | Column Name           | Column Order | Hide |
    {"Project": "Default", "Column Name": "No",                        "Column Order": 0,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Dashboard Name",            "Column Order": 1,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Widget Name",               "Column Order": 2,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Campaigns",                 "Column Order": 3,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Tag",                       "Column Order": 4,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Channel",                   "Column Order": 5,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Type",                      "Column Order": 6,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Date",                      "Column Order": 7,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Time",                      "Column Order": 8,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Hour",                      "Column Order": 9,  "Hide": "No"},
    {"Project": "Default", "Column Name": "Official Account",          "Column Order": 10, "Hide": "No"},
    {"Project": "Default", "Column Name": "Author",                    "Column Order": 11, "Hide": "No"},
    {"Project": "Default", "Column Name": "Creator Type",              "Column Order": 12, "Hide": "No"},
    {"Project": "Default", "Column Name": "Verified Account",          "Column Order": 13, "Hide": "No"},
    {"Project": "Default", "Column Name": "Title",                     "Column Order": 14, "Hide": "No"},
    {"Project": "Default", "Column Name": "Noise Tag",                 "Column Order": 15, "Hide": "No"},
    {"Project": "Default", "Column Name": "Content",                   "Column Order": 16, "Hide": "No"},
    {"Project": "Default", "Column Name": "Issue",                     "Column Order": 17, "Hide": "No"},
    {"Project": "Default", "Column Name": "Sub Issue",                 "Column Order": 18, "Hide": "No"},
    {"Project": "Default", "Column Name": "Link URL",                  "Column Order": 19, "Hide": "No"},
    {"Project": "Default", "Column Name": "Sentiment",                 "Column Order": 20, "Hide": "No"},
    {"Project": "Default", "Column Name": "Buzz",                      "Column Order": 21, "Hide": "No"},
    {"Project": "Default", "Column Name": "Followers",                 "Column Order": 22, "Hide": "No"},
    {"Project": "Default", "Column Name": "Image Description",         "Column Order": 23, "Hide": "No"},
    {"Project": "Default", "Column Name": "Language",                  "Column Order": 24, "Hide": "No"},
    {"Project": "Default", "Column Name": "Country",                   "Column Order": 25, "Hide": "No"},
    {"Project": "Default", "Column Name": "Extracted Text",            "Column Order": 26, "Hide": "No"},
    {"Project": "Default", "Column Name": "Original Reach",            "Column Order": 27, "Hide": "No"},
    {"Project": "Default", "Column Name": "Viral Reach",               "Column Order": 28, "Hide": "No"},
    {"Project": "Default", "Column Name": "Potential Reach",           "Column Order": 29, "Hide": "No"},
    {"Project": "Default", "Column Name": "Viral Score",               "Column Order": 30, "Hide": "No"},
    {"Project": "Default", "Column Name": "Engagement",                "Column Order": 31, "Hide": "No"},
    {"Project": "Default", "Column Name": "Replies",                   "Column Order": 32, "Hide": "No"},
    {"Project": "Default", "Column Name": "Retweets",                  "Column Order": 33, "Hide": "No"},
    {"Project": "Default", "Column Name": "Comments",                  "Column Order": 34, "Hide": "No"},
    {"Project": "Default", "Column Name": "Likes",                     "Column Order": 35, "Hide": "No"},
    {"Project": "Default", "Column Name": "Shares",                    "Column Order": 36, "Hide": "No"},
    {"Project": "Default", "Column Name": "Views",                     "Column Order": 37, "Hide": "No"},
    {"Project": "Default", "Column Name": "Ad Value",                  "Column Order": 38, "Hide": "No"},
    {"Project": "Default", "Column Name": "PR Value",                  "Column Order": 39, "Hide": "No"},
    {"Project": "Default", "Column Name": "Readership",                "Column Order": 40, "Hide": "No"},
    {"Project": "Default", "Column Name": "Author Like",               "Column Order": 41, "Hide": "No"},
    {"Project": "Default", "Column Name": "Circulation",               "Column Order": 42, "Hide": "No"},
    {"Project": "Default", "Column Name": "Media Tier",                "Column Order": 43, "Hide": "No"},
    {"Project": "Default", "Column Name": "Media Name",                "Column Order": 44, "Hide": "No"},
    {"Project": "Default", "Column Name": "Link URL Tracking",         "Column Order": 45, "Hide": "No"},
    {"Project": "Default", "Column Name": "Image URL",                 "Column Order": 46, "Hide": "No"},
    {"Project": "Default", "Column Name": "Video URL",                 "Column Order": 47, "Hide": "No"},
    {"Project": "Default", "Column Name": "Channel URL",               "Column Order": 48, "Hide": "No"},
    {"Project": "Default", "Column Name": "Media Type",                "Column Order": 49, "Hide": "No"},
    {"Project": "Default", "Column Name": "Spokesperson",              "Column Order": 50, "Hide": "No"},
    {"Project": "Default", "Column Name": "Aspect Based Sentiment",    "Column Order": 51, "Hide": "No"},
    {"Project": "Default", "Column Name": "Generic Sentiment Analysis","Column Order": 52, "Hide": "No"},
    {"Project": "Default", "Column Name": "Topic Extraction",          "Column Order": 53, "Hide": "No"},
    {"Project": "Default", "Column Name": "People Extraction",         "Column Order": 54, "Hide": "No"},
    {"Project": "Default", "Column Name": "Entity Extraction",         "Column Order": 55, "Hide": "No"},
    {"Project": "Default", "Column Name": "Noun",                      "Column Order": 56, "Hide": "No"},
    {"Project": "Default", "Column Name": "Sentence Type Classification", "Column Order": 57, "Hide": "No"},
    {"Project": "Default", "Column Name": "Labels",                    "Column Order": 58, "Hide": "No"},
    {"Project": "Default", "Column Name": "Age",                       "Column Order": 59, "Hide": "No"},
    {"Project": "Default", "Column Name": "Gender",                    "Column Order": 60, "Hide": "No"},
    {"Project": "Default", "Column Name": "Location",                  "Column Order": 61, "Hide": "No"},
    {"Project": "Default", "Column Name": "Rules Affected",            "Column Order": 62, "Hide": "No"},
    {"Project": "Default", "Column Name": "Rules Affected Words",      "Column Order": 63, "Hide": "No"},
]
